/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Contract } from "./ERC20Contract.js";
export * as factories from "./factories/index.js";
export { ERC20Contract__factory } from "./factories/ERC20Contract__factory.js";
