#===== Rust builder =====
FROM ubuntu:22.04 AS rust-builder
LABEL maintainer="ReDeFi"

ENV CARGO_HOME="/cargo-home"
ENV PATH="/cargo-home/bin:$PATH"
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get install -y curl cmake pkg-config libssl-dev git clang llvm libudev-dev protobuf-compiler && \
    apt-get clean && \
    rm -r /var/lib/apt/lists/*

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none

# ===== BUILD =====
FROM rust-builder AS builder-parachain-bin

RUN mkdir /redefi

ARG REDEFI_PARACHAIN

RUN git clone -b $REDEFI_PARACHAIN --depth 1 https://github.com/ReDeFi-Blockchain/redefi-parachain.git /redefi-parachain-src && \
    cd /redefi-parachain-src && \
    CARGO_INCREMENTAL=0 cargo build --profile=release --locked && \
    mv ./target/release/redefi-collator /redefi/ && \
    mv ./target/release/wbuild/redefi-runtime/redefi_runtime.compact.compressed.wasm /redefi/ 


#===== BIN ======
FROM ubuntu:22.04

RUN mkdir /redefi

COPY --from=builder-parachain-bin /redefi/redefi-collator /bin/redefi-collator
COPY --from=builder-parachain-bin /redefi/redefi_runtime.compact.compressed.wasm /redefi/redefi_runtime.compact.compressed.wasm

ENTRYPOINT ["/bin/redefi-collator"]
