#===== Rust builder =====
FROM ubuntu:22.04 as rust-builder
LABEL maintainer="ReDeFi"

ENV CARGO_HOME="/cargo-home"
ENV PATH="/cargo-home/bin:$PATH"
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get install -y curl cmake pkg-config libssl-dev git clang llvm libudev-dev protobuf-compiler && \
    apt-get clean && \
    rm -r /var/lib/apt/lists/*

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none

ARG RUST_TOOLCHAIN

RUN echo "Using Rust $RUST_TOOLCHAIN" && \
    rustup toolchain install $RUST_TOOLCHAIN && \
    rustup target add wasm32-unknown-unknown --toolchain $RUST_TOOLCHAIN && \
    rustup default $RUST_TOOLCHAIN && \
    rustup component add --toolchain $RUST_TOOLCHAIN rust-src \
    rustup target list --installed && \
    rustup show

# ===== BUILD =====
FROM rust-builder as builder-parachain-bin

RUN mkdir /redefi

ARG REDEFI_PARACHAIN

RUN git clone -b $REDEFI_PARACHAIN --depth 1 https://github.com/ReDeFi-Blockchain/redefi-parachain.git /redefi-parachain-src && \
    cd /redefi-parachain-src && \
    CARGO_INCREMENTAL=0 cargo build --profile=release --locked && \
    mv ./target/release/redefi-collator /redefi/ 

#===== BIN ======
FROM ubuntu:22.04

COPY --from=builder-parachain-bin /redefi/redefi-collator /bin/redefi-collator

ENTRYPOINT ["/bin/redefi-collator"]
