#===== Rust builder =====
FROM ubuntu:22.04 AS rust-builder
LABEL maintainer="ReDeFi"

ENV CARGO_HOME="/cargo-home"
ENV PATH="/cargo-home/bin:$PATH"
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get install -y curl cmake pkg-config libssl-dev git clang llvm libudev-dev protobuf-compiler && \
    apt-get clean && \
    rm -r /var/lib/apt/lists/*

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none

# ===== BUILD =====
FROM rust-builder AS builder-relay-bin

RUN mkdir /redefi

ARG REDEFI_RELAY

RUN git clone -b $REDEFI_RELAY --depth 1 https://github.com/ReDeFi-Blockchain/redefi-relay-node.git /redefi-relay-node-src && \
    cd /redefi-relay-node-src && \
    CARGO_INCREMENTAL=0 cargo build --profile=release --locked && \
    mv ./target/release/polkadot /redefi/ && \
    mv ./target/release/polkadot-execute-worker /redefi/ && \
    mv ./target/release/polkadot-prepare-worker /redefi/

#===== BIN ======

FROM ubuntu:22.04

COPY --from=builder-relay-bin /redefi/polkadot /bin/polkadot
COPY --from=builder-relay-bin /redefi/polkadot-execute-worker /bin/polkadot-execute-worker
COPY --from=builder-relay-bin /redefi/polkadot-prepare-worker /bin/polkadot-prepare-worker

ENTRYPOINT ["/bin/polkadot"]
