#===== Rust builder =====
FROM ubuntu:22.04 AS rust-builder
LABEL maintainer="ReDeFi"

ENV CARGO_HOME="/cargo-home"
ENV PATH="/cargo-home/bin:$PATH"
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get install -y curl cmake pkg-config libssl-dev git clang llvm libudev-dev protobuf-compiler && \
    apt-get clean && \
    rm -r /var/lib/apt/lists/*

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none

# ===== BUILD =====
FROM rust-builder AS builder-runtime-wasm

ARG REDEFI_RELAY_RUNTIME

RUN git clone -b $REDEFI_RELAY_RUNTIME --depth 1 https://github.com/ReDeFi-Blockchain/redefi-relay-runtime.git /redefi-relay-runtime-src && \
    cd /redefi-relay-runtime-src && \
    CARGO_INCREMENTAL=0 cargo build --profile=release --features=fast-runtime --locked

#===== BIN ======

FROM ubuntu:22.04

RUN mkdir /redefi

COPY --from=builder-runtime-wasm /redefi-relay-runtime-src/target/release/wbuild/redefi-runtime/redefi_runtime.compact.compressed.wasm /redefi/redefi_runtime.compact.compressed.wasm

