# https://cryptousetech.atlassian.net/wiki/spaces/CI/pages/2586837012/Code+style+testing
# Nested workflow for checks related to formatting Rust code 

name: codestyle-parachain

# Triger: only call from main workflow(re-usable workflows)
on:
  workflow_call:
    inputs:
      relay-node-version:
        type: string
        description: relay branch to build
        required: true
      relay-runtime-version:
        type: string
        description: relay runtime branch to build
        required: true
      parachain-version:
        type: string
        description: parachain branch to build
        required: true
  workflow_dispatch:            

jobs:
  rustfmt:
    runs-on: [ self-hosted ]
    steps:
      - name: Clean Workspace
        uses: AutoModality/action-clean@v1.1.0
      - uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.head_ref }}          

      - name: Checkout parachain
        uses: actions/checkout@v4.1.7
        with:
          repository: 'ReDeFi-Blockchain/redefi-parachain'
          path: 'redefi-parachain'
          ref: ${{ inputs.parachain-version }}

      - name: Run cargo fmt for redefi-parachain
        working-directory: redefi-parachain
        run: cargo fmt -- --check   # In that mode it returns only exit code.

      - name: Cargo fmt state for redefi-parachain
        if: success()
        run: echo "Nothing to do. Command 'cargo fmt -- --check' returned exit code 0."
